output "control_kubeconfig" {
  description = "Kubeconfig for the control cluster."
  value       = module.cluster_control.kubeconfig
  sensitive   = true
}

output "ssh_private_key_generated" {
  description = "SSH private key generated by the cluster module (only set if no keypair_name was provided)."
  value       = module.cluster_control.ssh_private_key_generated
  sensitive   = true
}
