output "control_plane_external_ip" {
  description = "Control plane node IPv4 address on the external network (from the cluster module)."
  value       = module.cluster_control.control_plane_external_ip
}

output "ssh_private_key_generated" {
  description = "SSH private key generated by the cluster module (only set if no keypair_name was provided)."
  value       = module.cluster_control.ssh_private_key_generated
  sensitive   = true
}
