---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      interval: 1h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.19.0
  install:
    createNamespace: true
  interval: 1h0m0s
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    provider:
      name: google
    extraArgs:
    - --google-project=timebertt-dhbw

    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secrets/service-account/service-account.json
    extraVolumeMounts:
    - name: clouddns-credentials
      mountPath: /etc/secrets/service-account
      readOnly: true
    extraVolumes:
    - name: clouddns-credentials
      secret:
        secretName: google-clouddns

    logLevel: info
    policy: sync
    interval: 5m
    triggerLoopOnEvent: true
    sources:
    - ingress
    - service

    registry: txt
    txtOwnerId: timebertt # <cluster-name>, e.g., student-abcd
